theme: jekyll-theme-architect
title: "Quentin McTeer's Data Science Portfolio"
description: "The complete collection of my data cleaning, exploration, causal inference, and maching learning projects."
