theme: jekyll-theme-cayman
title: "My Data Science Portfolio"
description: "The complete collection of Quentin McTeer's data cleaning, exploration, causal inference, NLP, and machine learning projects."
